### ISSUE TITLE
Spark DB Generate

### ISSUE THREAD

**Issue by MHDOB** [kennethmyhra/spark-example#1]
Hello there,
Can you help with how to generate collection in our MongoDB?

**Comment by kennethmyhra** [comment]
Take a look at https://github.com/FirelyTeam/spark/blob/master/.docker/linux/mongorestore.sh.

Remeber to set --archive to appropriate FHIR version you want to restore, that could be:
* dstu2.archive.gz for FHIR DSTU2
* stu3.archive.gz for FHIR STU3
* r4.archive.gz for FHIR R4
